import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'arroww_icon.dart';

/// Renders the Play Store listing icon (512x512, the exact size Google
/// Play requires for the store listing icon field) straight from the
/// same vector geometry as the real launcher icon, so it matches
/// on-device branding exactly rather than being a resampled copy.
///
/// This does NOT touch assets/icon/ (the real launcher-icon build
/// input, generated by render_icons.dart) or the generated Android
/// mipmap resources - it only writes a separate file for uploading to
/// Play Console later.
///
/// Run with:
///   flutter test tool/launcher_icon/render_store_icon.dart
Future<void> main() async {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('render the 512x512 Play Store listing icon', () async {
    const size = 512.0;
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder, const Rect.fromLTWH(0, 0, size, size));
    ArrowwIcon.paintFull(canvas, size);
    final picture = recorder.endRecording();
    final image = await picture.toImage(size.round(), size.round());
    final data = await image.toByteData(format: ui.ImageByteFormat.png);

    final file = File('docs/play_store_icon_512.png');
    await file.parent.create(recursive: true);
    await file.writeAsBytes(data!.buffer.asUint8List());
    debugPrint('wrote ${file.path} (512x512)');
  });
}
