import '../models/arrow_model.dart';
import '../models/level_model.dart';

/// Static level definitions used until a real level loader exists.
///
/// Levels 1-12 are single "chains": the last-listed arrow always
/// starts unblocked, and removing it unblocks the previous one, and
/// so on. Levels 13+ combine multiple independent chains (placed in
/// disjoint row bands so they never interfere with each other) and,
/// from level 28 on, a "gate" arrow whose column-based dependency
/// transitively requires two whole chains to be cleared first. In
/// every level [LevelModel.optimalMoves] equals the arrow count,
/// since a valid removal order exists where each arrow needs exactly
/// one successful tap.
class LevelData {
  LevelData._();

  static final List<LevelModel> levels = [
    LevelModel(
      id: 1,
      name: 'Level 1',
      gridSize: 3,
      difficulty: 1,
      optimalMoves: 2,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 2, col: 1, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 2,
      name: 'Level 2',
      gridSize: 4,
      difficulty: 2,
      optimalMoves: 3,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 2, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a3', row: 2, col: 3, direction: ArrowDirection.up),
      ],
    ),
    LevelModel(
      id: 3,
      name: 'Level 3',
      gridSize: 4,
      difficulty: 3,
      optimalMoves: 4,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 2, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a3', row: 2, col: 3, direction: ArrowDirection.up),
        ArrowModel(id: 'a4', row: 1, col: 3, direction: ArrowDirection.left),
      ],
    ),
    LevelModel(
      id: 4,
      name: 'Level 4',
      gridSize: 4,
      difficulty: 4,
      optimalMoves: 5,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 2, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a3', row: 2, col: 3, direction: ArrowDirection.up),
        ArrowModel(id: 'a4', row: 1, col: 3, direction: ArrowDirection.left),
        ArrowModel(id: 'a5', row: 1, col: 2, direction: ArrowDirection.down),
      ],
    ),
    LevelModel(
      id: 5,
      name: 'Level 5',
      gridSize: 4,
      difficulty: 5,
      optimalMoves: 6,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 2, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a3', row: 2, col: 3, direction: ArrowDirection.up),
        ArrowModel(id: 'a4', row: 1, col: 3, direction: ArrowDirection.left),
        ArrowModel(id: 'a5', row: 1, col: 2, direction: ArrowDirection.down),
        ArrowModel(id: 'a6', row: 3, col: 2, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 6,
      name: 'Level 6',
      gridSize: 4,
      difficulty: 6,
      optimalMoves: 7,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 2, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a3', row: 2, col: 3, direction: ArrowDirection.up),
        ArrowModel(id: 'a4', row: 1, col: 3, direction: ArrowDirection.left),
        ArrowModel(id: 'a5', row: 1, col: 2, direction: ArrowDirection.down),
        ArrowModel(id: 'a6', row: 3, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 3, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 7,
      name: 'Level 7',
      gridSize: 5,
      difficulty: 7,
      optimalMoves: 8,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 1, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a4', row: 2, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a5', row: 2, col: 2, direction: ArrowDirection.down),
        ArrowModel(id: 'a6', row: 3, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 3, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a8', row: 4, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 8,
      name: 'Level 8',
      gridSize: 5,
      difficulty: 8,
      optimalMoves: 8,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.down),
        ArrowModel(id: 'a5', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 3, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 3, col: 4, direction: ArrowDirection.down),
      ],
    ),
    LevelModel(
      id: 9,
      name: 'Level 9',
      gridSize: 5,
      difficulty: 9,
      optimalMoves: 9,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 1, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a4', row: 2, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a5', row: 2, col: 2, direction: ArrowDirection.down),
        ArrowModel(id: 'a6', row: 3, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 3, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a8', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 4, col: 4, direction: ArrowDirection.down),
      ],
    ),
    LevelModel(
      id: 10,
      name: 'Level 10',
      gridSize: 5,
      difficulty: 10,
      optimalMoves: 9,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.down),
        ArrowModel(id: 'a5', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 3, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 3, col: 4, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 4, col: 4, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 11,
      name: 'Level 11',
      gridSize: 6,
      difficulty: 11,
      optimalMoves: 10,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.down),
        ArrowModel(id: 'a2', row: 1, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a4', row: 2, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a5', row: 2, col: 2, direction: ArrowDirection.down),
        ArrowModel(id: 'a6', row: 3, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 3, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a8', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 4, col: 4, direction: ArrowDirection.down),
        ArrowModel(id: 'a10', row: 5, col: 4, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 12,
      name: 'Level 12',
      gridSize: 6,
      difficulty: 12,
      optimalMoves: 10,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.down),
        ArrowModel(id: 'a5', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 3, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 3, col: 4, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 4, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 4, col: 5, direction: ArrowDirection.down),
      ],
    ),
    LevelModel(
      id: 13,
      name: 'Level 13',
      gridSize: 6,
      difficulty: 13,
      optimalMoves: 11,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a8', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a10', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 2, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 14,
      name: 'Level 14',
      gridSize: 6,
      difficulty: 14,
      optimalMoves: 12,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a11', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 2, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 15,
      name: 'Level 15',
      gridSize: 6,
      difficulty: 15,
      optimalMoves: 13,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a11', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a13', row: 3, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 16,
      name: 'Level 16',
      gridSize: 7,
      difficulty: 16,
      optimalMoves: 14,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 1, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a10', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a12', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a14', row: 3, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 17,
      name: 'Level 17',
      gridSize: 7,
      difficulty: 17,
      optimalMoves: 15,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 1, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a10', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a12', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a14', row: 3, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 3, col: 4, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 18,
      name: 'Level 18',
      gridSize: 7,
      difficulty: 18,
      optimalMoves: 16,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 1, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 1, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a11', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a13', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a15', row: 3, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 3, col: 4, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 19,
      name: 'Level 19',
      gridSize: 7,
      difficulty: 19,
      optimalMoves: 14,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a8', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a10', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 20,
      name: 'Level 20',
      gridSize: 7,
      difficulty: 20,
      optimalMoves: 15,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a8', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a10', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 2, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 21,
      name: 'Level 21',
      gridSize: 7,
      difficulty: 21,
      optimalMoves: 17,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a11', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 2, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 4, col: 4, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 22,
      name: 'Level 22',
      gridSize: 8,
      difficulty: 22,
      optimalMoves: 17,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a11', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 2, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 4, col: 4, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 23,
      name: 'Level 23',
      gridSize: 8,
      difficulty: 23,
      optimalMoves: 18,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a11', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a13', row: 3, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a18', row: 4, col: 4, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 24,
      name: 'Level 24',
      gridSize: 8,
      difficulty: 24,
      optimalMoves: 20,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 1, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a10', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a12', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a14', row: 3, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a18', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a19', row: 4, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a20', row: 4, col: 5, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 25,
      name: 'Level 25',
      gridSize: 8,
      difficulty: 25,
      optimalMoves: 18,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a8', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a10', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 5, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 5, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 5, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a18', row: 5, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 26,
      name: 'Level 26',
      gridSize: 8,
      difficulty: 26,
      optimalMoves: 19,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a11', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 5, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 5, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a18', row: 5, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a19', row: 5, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 27,
      name: 'Level 27',
      gridSize: 8,
      difficulty: 27,
      optimalMoves: 21,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a11', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 2, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 4, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a18', row: 5, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a19', row: 5, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a20', row: 5, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a21', row: 5, col: 3, direction: ArrowDirection.right),
      ],
    ),
    LevelModel(
      id: 28,
      name: 'Level 28',
      gridSize: 9,
      difficulty: 28,
      optimalMoves: 23,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a7', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a9', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a10', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a11', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a12', row: 2, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 4, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a18', row: 5, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a19', row: 5, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a20', row: 5, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a21', row: 5, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a22', row: 5, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a23', row: 6, col: 0, direction: ArrowDirection.up),
      ],
    ),
    LevelModel(
      id: 29,
      name: 'Level 29',
      gridSize: 9,
      difficulty: 29,
      optimalMoves: 24,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 1, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a10', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a12', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 2, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a14', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a18', row: 4, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a19', row: 5, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a20', row: 5, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a21', row: 5, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a22', row: 5, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a23', row: 5, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a24', row: 6, col: 0, direction: ArrowDirection.up),
      ],
    ),
    LevelModel(
      id: 30,
      name: 'Level 30',
      gridSize: 9,
      difficulty: 30,
      optimalMoves: 27,
      arrows: const [
        ArrowModel(id: 'a1', row: 0, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a2', row: 0, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a3', row: 1, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a4', row: 1, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a5', row: 0, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a6', row: 0, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a7', row: 1, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a8', row: 2, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a9', row: 2, col: 1, direction: ArrowDirection.down),
        ArrowModel(id: 'a10', row: 3, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a11', row: 3, col: 2, direction: ArrowDirection.up),
        ArrowModel(id: 'a12', row: 2, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a13', row: 2, col: 3, direction: ArrowDirection.down),
        ArrowModel(id: 'a14', row: 3, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a15', row: 4, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a16', row: 4, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a17', row: 4, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a18', row: 4, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a19', row: 4, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a20', row: 4, col: 5, direction: ArrowDirection.right),
        ArrowModel(id: 'a21', row: 5, col: 0, direction: ArrowDirection.right),
        ArrowModel(id: 'a22', row: 5, col: 1, direction: ArrowDirection.right),
        ArrowModel(id: 'a23', row: 5, col: 2, direction: ArrowDirection.right),
        ArrowModel(id: 'a24', row: 5, col: 3, direction: ArrowDirection.right),
        ArrowModel(id: 'a25', row: 5, col: 4, direction: ArrowDirection.right),
        ArrowModel(id: 'a26', row: 5, col: 5, direction: ArrowDirection.right),
        ArrowModel(id: 'a27', row: 6, col: 0, direction: ArrowDirection.up),
      ],
    ),
  ];

  static LevelModel byId(int id) {
    return levels.firstWhere(
      (level) => level.id == id,
      orElse: () => throw ArgumentError('Unknown level id: $id'),
    );
  }
}
